#!/bin/bash
minute=$(date '+%M')
if [[ $minute =~ [05]$ ]]; then
 cd /var/lib/openshift/57ffefa37628e1ae2d000144/app-root/repo
 echo "Checking Dvla, please wait..."
 mvn exec:java -Dexec.mainClass="uk.gov.direct.driverpracticaltest.CheckTestDate"
 echo "Dvla check completed"
fi
